### ISSUE TITLE
Support specifying no rsyslog_mods

### ISSUE THREAD

**Issue by chancez** [robertdebock/ansible-role-rsyslog#11]
## Proposed feature

Currently the assertions check if `rsyslog_mods` is defined/empty, and fails if it there isn't at least 1 module loaded. However, this validation seems unnecessary none of the allowed `rsyslog_mods` are strictly required.

I'm using rsyslog purely as a receiver of logs from other hosts to be forwarded to another log processing tool.

I'm using `journald` to provide `/dev/log` so I don't need `immuxsock`. I don't want to use `imjournal` because I don't want the host's journal logs to go to rsyslog. `imklog` and `immark` aren't really needed for me either.

I propose the validation on `rsyslog_mods` is either removed or changed to allow specifying an empty list.

**Comment by chancez** [comment]
Also, when `immuxsocket` _isn't_ specified, you get this error:
```
invalid or yet-unknown config file command 'OmitLocalLogging'
```

because https://github.com/robertdebock/ansible-role-rsyslog/blob/master/templates/legacy_rsyslog.conf.j2#L40 is set when the module _isnt_ loaded, but it's an option that only applies when that module is loaded.

**Comment by isuftin** [comment]
@chancez  - I know this issue is now years old but I was able to get around this in a hacky way...

```
rsyslog_rsyslog_d_files:
  # We have to do it this way because of:
  # https://github.com/robertdebock/ansible-role-rsyslog/issues/11
  # https://github.com/robertdebock/ansible-role-rsyslog/pull/12
  - omit_local_logging_fix:
      content: $OmitLocalLogging on
```
