### ISSUE TITLE
failing on assert.yml in version 4..4.1

### ISSUE THREAD

**Issue by shaunrampersad** [robertdebock/ansible-role-rsyslog#31]
## Describe the bug
play fails on assert.yml.

## Playbook

```yaml
---
- hosts: all
  become: true
  tasks:

    - name: install robertdebock.rsyslog
      include_role:
        name: robertdebock.rsyslog

```

## Output

```
ERROR! this task 'ansible.builtin.import_tasks' has extra params, which is only allowed in the following modules: ansible.windows.win_command, win_command, win_shell, include_vars, group_by, ansible.windows.win_shell, add_host, shell, import_tasks, include_tasks, script, raw, set_fact, import_role, command, meta, include_role, include

The error appears to be in '/home/user/code/master/roles/robertdebock.rsyslog/tasks/main.yml': line 4, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: import assert.yml
  ^ here
```

## Environment

- Control node OS: CentOS Linux release 7.7.1908 (Core)
- Control node Ansible version: ansible 2.10.3
- Managed node OS: Centos7

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
